config/routes.rb
TradingDiary::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"

  resources :users

  resources :trades

  resources :holdings

end

app/models/holding.rb
class Holding < ActiveRecord::Base
  attr_accessible :avg_price, :company_id, :date_sold, :purchase_date, :quantity, :user_id
end

app/models/trade.rb
class Trade < ActiveRecord::Base
  attr_accessible :brokerage, :company_id, :price, :quantity, :trade_date, :type, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  # GET /holdings
  # GET /holdings.json
  def index
    @holdings = Holding.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @holdings }
    end
  end

  # GET /holdings/1
  # GET /holdings/1.json
  def show
    @holding = Holding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @holding }
    end
  end

  # GET /holdings/new
  # GET /holdings/new.json
  def new
    @holding = Holding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @holding }
    end
  end

  # GET /holdings/1/edit
  def edit
    @holding = Holding.find(params[:id])
  end

  # POST /holdings
  # POST /holdings.json
  def create
    @holding = Holding.new(params[:holding])

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding, notice: 'Holding was successfully created.' }
        format.json { render json: @holding, status: :created, location: @holding }
      else
        format.html { render action: "new" }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /holdings/1
  # PUT /holdings/1.json
  def update
    @holding = Holding.find(params[:id])

    respond_to do |format|
      if @holding.update_attributes(params[:holding])
        format.html { redirect_to @holding, notice: 'Holding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1
  # DELETE /holdings/1.json
  def destroy
    @holding = Holding.find(params[:id])
    @holding.destroy

    respond_to do |format|
      format.html { redirect_to holdings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Trading Diary"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/holdings/_form.html.erb
<%= form_for(@holding) do |f| %>
  <% if @holding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@holding.errors.count, "error") %> prohibited this holding from being saved:</h2>

      <ul>
      <% @holding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.number_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :avg_price %><br />
    <%= f.text_field :avg_price %>
  </div>
  <div class="field">
    <%= f.label :date_sold %><br />
    <%= f.date_select :date_sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/holdings/edit.html.erb
<h1>Editing holding</h1>

<%= render 'form' %>

<%= link_to 'Show', @holding %> |
<%= link_to 'Back', holdings_path %>

app/views/holdings/index.html.erb
<h1>Listing holdings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Purchase date</th>
    <th>Company</th>
    <th>Quantity</th>
    <th>Avg price</th>
    <th>Date sold</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @holdings.each do |holding| %>
  <tr>
    <td><%= holding.user_id %></td>
    <td><%= holding.purchase_date %></td>
    <td><%= holding.company_id %></td>
    <td><%= holding.quantity %></td>
    <td><%= holding.avg_price %></td>
    <td><%= holding.date_sold %></td>
    <td><%= link_to 'Show', holding %></td>
    <td><%= link_to 'Edit', edit_holding_path(holding) %></td>
    <td><%= link_to 'Destroy', holding, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Holding', new_holding_path %>

app/views/holdings/new.html.erb
<h1>New holding</h1>

<%= render 'form' %>

<%= link_to 'Back', holdings_path %>

app/views/holdings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @holding.user_id %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @holding.purchase_date %>
</p>

<p>
  <b>Company:</b>
  <%= @holding.company_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @holding.quantity %>
</p>

<p>
  <b>Avg price:</b>
  <%= @holding.avg_price %>
</p>

<p>
  <b>Date sold:</b>
  <%= @holding.date_sold %>
</p>


<%= link_to 'Edit', edit_holding_path(@holding) %> |
<%= link_to 'Back', holdings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>This is the About Us page for the Trading Diary application.</p>		

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>This is the help page for the Trading Diary application.</p>		

app/views/static_pages/home.html.erb
<h1>Trading Diary</h1>
<p>This is the home page for the Trading Diary application.</p>		

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :trade_date %><br />
    <%= f.date_select :trade_date %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :trade_type %><br />
    <%= f.text_field :trade_type %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :brokerage %><br />
    <%= f.text_field :brokerage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <tr>
    <th>User</th>
    <th>Trade date</th>
    <th>Company</th>
    <th>Quantity</th>
    <th>Type</th>
    <th>Price</th>
    <th>Brokerage</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trades.each do |trade| %>
  <tr>
    <td><%= trade.user_id %></td>
    <td><%= trade.trade_date %></td>
    <td><%= trade.company_id %></td>
    <td><%= trade.quantity %></td>
    <td><%= trade.trade_type %></td>
    <td><%= trade.price %></td>
    <td><%= trade.brokerage %></td>
    <td><%= link_to 'Show', trade %></td>
    <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
    <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @trade.user_id %>
</p>

<p>
  <b>Trade date:</b>
  <%= @trade.trade_date %>
</p>

<p>
  <b>Company:</b>
  <%= @trade.company_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @trade.quantity %>
</p>

<p>
  <b>Type:</b>
  <%= @trade.type %>
</p>

<p>
  <b>Price:</b>
  <%= @trade.price %>
</p>

<p>
  <b>Brokerage:</b>
  <%= @trade.brokerage %>
</p>


<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>